"""
Asaas API client — low-level HTTP wrapper.

Docs: https://docs.asaas.com/
Base URLs:
  Production: https://api.asaas.com/v3
  Sandbox:    https://sandbox.asaas.com/api/v3
"""

import logging
from typing import Optional, Dict, Any, List

import httpx

from config import settings

logger = logging.getLogger(__name__)

_TIMEOUT = 30  # seconds


class AsaasError(Exception):
    """Raised when Asaas API returns an error."""
    def __init__(self, status_code: int, errors: list, description: str = ""):
        self.status_code = status_code
        self.errors = errors
        super().__init__(f"Asaas API error {status_code}: {description or errors}")


class AsaasClient:
    """HTTP client for the Asaas payment API."""

    def __init__(self):
        self.api_key = settings.asaas_api_key
        if settings.asaas_sandbox:
            self.base_url = "https://sandbox.asaas.com/api/v3"
        else:
            self.base_url = "https://api.asaas.com/v3"

    @property
    def _headers(self) -> dict:
        return {
            "access_token": self.api_key,
            "Content-Type": "application/json",
        }

    def _request(self, method: str, path: str, **kwargs) -> dict:
        """Make an HTTP request to Asaas and return parsed JSON."""
        url = f"{self.base_url}{path}"
        try:
            with httpx.Client(timeout=_TIMEOUT) as client:
                response = client.request(
                    method, url, headers=self._headers, **kwargs
                )
            data = response.json()

            if response.status_code >= 400:
                errors = data.get("errors", [])
                desc = errors[0].get("description", "") if errors else str(data)
                logger.error(f"Asaas {method} {path} → {response.status_code}: {desc}")
                raise AsaasError(response.status_code, errors, desc)

            return data

        except httpx.RequestError as e:
            logger.error(f"Asaas request failed: {e}")
            raise AsaasError(0, [], f"Connection error: {e}")

    # ── Customers ──────────────────────────────────────────────

    def create_customer(
        self, name: str, email: str, cpf_cnpj: Optional[str] = None
    ) -> dict:
        """Create an Asaas customer. Returns {id, name, email, ...}."""
        payload: Dict[str, Any] = {"name": name, "email": email}
        if cpf_cnpj:
            payload["cpfCnpj"] = cpf_cnpj
        return self._request("POST", "/customers", json=payload)

    def get_customer(self, customer_id: str) -> dict:
        return self._request("GET", f"/customers/{customer_id}")

    # ── Subscriptions ──────────────────────────────────────────

    def create_subscription(
        self,
        customer_id: str,
        value: float,
        cycle: str = "MONTHLY",
        billing_type: str = "UNDEFINED",
        description: str = "",
        next_due_date: Optional[str] = None,
    ) -> dict:
        """
        Create a subscription.
        billing_type: UNDEFINED lets customer choose PIX/boleto/card.
        cycle: MONTHLY, QUARTERLY, SEMIANNUALLY, YEARLY
        next_due_date: YYYY-MM-DD (first charge date)
        """
        payload: Dict[str, Any] = {
            "customer": customer_id,
            "billingType": billing_type,
            "value": value,
            "cycle": cycle,
            "description": description,
        }
        if next_due_date:
            payload["nextDueDate"] = next_due_date
        return self._request("POST", "/subscriptions", json=payload)

    def get_subscription(self, subscription_id: str) -> dict:
        return self._request("GET", f"/subscriptions/{subscription_id}")

    def update_subscription(self, subscription_id: str, **kwargs) -> dict:
        """Update subscription fields (value, billingType, cycle, etc.)."""
        return self._request(
            "POST", f"/subscriptions/{subscription_id}", json=kwargs
        )

    def cancel_subscription(self, subscription_id: str) -> dict:
        """Cancel/delete a subscription."""
        return self._request("DELETE", f"/subscriptions/{subscription_id}")

    def list_subscription_payments(
        self, subscription_id: str, offset: int = 0, limit: int = 50
    ) -> dict:
        """List payments generated by a subscription."""
        return self._request(
            "GET",
            f"/subscriptions/{subscription_id}/payments",
            params={"offset": offset, "limit": limit},
        )

    # ── Payments ───────────────────────────────────────────────

    def get_payment(self, payment_id: str) -> dict:
        return self._request("GET", f"/payments/{payment_id}")

    def list_customer_payments(
        self, customer_id: str, offset: int = 0, limit: int = 20
    ) -> dict:
        """List payments for a customer (billing history)."""
        return self._request(
            "GET",
            "/payments",
            params={"customer": customer_id, "offset": offset, "limit": limit},
        )

    def refund_payment(self, payment_id: str, value: Optional[float] = None) -> dict:
        """Refund a payment (full or partial)."""
        payload: Dict[str, Any] = {}
        if value:
            payload["value"] = value
        return self._request("POST", f"/payments/{payment_id}/refund", json=payload)

    # ── Payment Links (for updating payment method) ────────────

    def get_payment_invoice_url(self, payment_id: str) -> Optional[str]:
        """Get the hosted payment page URL for a specific payment."""
        payment = self.get_payment(payment_id)
        return payment.get("invoiceUrl")
