"""add company data fields to user model

Revision ID: 0dfa6216e4e5
Revises: d6674609c7b3
Create Date: 2026-03-02 17:30:57.082008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfa6216e4e5'
down_revision: Union[str, None] = 'd6674609c7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_known_items_id'), 'known_items', ['id'], unique=False)
    op.add_column('users', sa.Column('trade_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('cnae_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('cnae_description', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('company_address_street', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('company_address_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('company_address_complement', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('company_address_district', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('company_address_city', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('company_address_state', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('company_address_zip', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('capital_social', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('users', sa.Column('company_size', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('legal_nature', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('company_phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('company_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('company_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('company_opened_at', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_simples_nacional', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_mei', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_mei')
    op.drop_column('users', 'is_simples_nacional')
    op.drop_column('users', 'company_opened_at')
    op.drop_column('users', 'company_status')
    op.drop_column('users', 'company_email')
    op.drop_column('users', 'company_phone')
    op.drop_column('users', 'legal_nature')
    op.drop_column('users', 'company_size')
    op.drop_column('users', 'capital_social')
    op.drop_column('users', 'company_address_zip')
    op.drop_column('users', 'company_address_state')
    op.drop_column('users', 'company_address_city')
    op.drop_column('users', 'company_address_district')
    op.drop_column('users', 'company_address_complement')
    op.drop_column('users', 'company_address_number')
    op.drop_column('users', 'company_address_street')
    op.drop_column('users', 'cnae_description')
    op.drop_column('users', 'cnae_code')
    op.drop_column('users', 'trade_name')
    op.drop_index(op.f('ix_known_items_id'), table_name='known_items')
    # ### end Alembic commands ###
