"""add_multi_org_support

Revision ID: 83d1d05da3fc
Revises: ac7c62914c7f
Create Date: 2026-03-03 09:18:06.323871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d1d05da3fc'
down_revision: Union[str, None] = 'ac7c62914c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=50), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('cnae_code', sa.String(length=20), nullable=True),
    sa.Column('cnae_description', sa.String(length=500), nullable=True),
    sa.Column('company_address_street', sa.String(length=500), nullable=True),
    sa.Column('company_address_number', sa.String(length=20), nullable=True),
    sa.Column('company_address_complement', sa.String(length=255), nullable=True),
    sa.Column('company_address_district', sa.String(length=255), nullable=True),
    sa.Column('company_address_city', sa.String(length=255), nullable=True),
    sa.Column('company_address_state', sa.String(length=2), nullable=True),
    sa.Column('company_address_zip', sa.String(length=10), nullable=True),
    sa.Column('capital_social', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('company_size', sa.String(length=100), nullable=True),
    sa.Column('legal_nature', sa.String(length=255), nullable=True),
    sa.Column('company_phone', sa.String(length=50), nullable=True),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('company_status', sa.String(length=50), nullable=True),
    sa.Column('company_opened_at', sa.String(length=20), nullable=True),
    sa.Column('is_simples_nacional', sa.Boolean(), nullable=True),
    sa.Column('is_mei', sa.Boolean(), nullable=True),
    sa.Column('qsa_partners', sa.JSON(), nullable=True),
    sa.Column('cnaes_secundarios', sa.JSON(), nullable=True),
    sa.Column('company_address_type', sa.String(length=50), nullable=True),
    sa.Column('is_headquarters', sa.Boolean(), nullable=True),
    sa.Column('ibge_code', sa.String(length=10), nullable=True),
    sa.Column('regime_tributario', sa.String(length=50), nullable=True),
    sa.Column('simples_desde', sa.String(length=20), nullable=True),
    sa.Column('simples_excluido_em', sa.String(length=20), nullable=True),
    sa.Column('main_partner_name', sa.String(length=500), nullable=True),
    sa.Column('main_partner_qualification', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_cnpj'), 'organizations', ['cnpj'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('org_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_invitations_id'), 'org_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_org_invitations_inviter_user_id'), 'org_invitations', ['inviter_user_id'], unique=False)
    op.create_index(op.f('ix_org_invitations_organization_id'), 'org_invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_org_invitations_target_email'), 'org_invitations', ['target_email'], unique=False)
    op.create_index(op.f('ix_org_invitations_target_user_id'), 'org_invitations', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_org_invitations_token'), 'org_invitations', ['token'], unique=True)
    op.create_table('org_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_org')
    )
    op.create_index('idx_org_membership_org_active', 'org_memberships', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_org_memberships_id'), 'org_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_org_memberships_organization_id'), 'org_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_org_memberships_user_id'), 'org_memberships', ['user_id'], unique=False)
    op.add_column('subscriptions', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('active_org_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_active_org_id'), 'users', ['active_org_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['active_org_id'], ['id'])
    # ### end Alembic commands ###

    # =========================================================================
    # DATA MIGRATION: Populate organizations from existing users
    # =========================================================================
    conn = op.get_bind()

    # Step 1: Create Organization records from owners (parent_user_id IS NULL)
    # These are the "org owners" — each unique CNPJ becomes one Organization
    conn.execute(sa.text("""
        INSERT INTO organizations (
            company_name, cnpj, trade_name, cnae_code, cnae_description,
            company_address_street, company_address_number, company_address_complement,
            company_address_district, company_address_city, company_address_state,
            company_address_zip, capital_social, company_size, legal_nature,
            company_phone, company_email, company_status, company_opened_at,
            is_simples_nacional, is_mei, qsa_partners, cnaes_secundarios,
            company_address_type, is_headquarters, ibge_code, regime_tributario,
            simples_desde, simples_excluido_em, main_partner_name,
            main_partner_qualification, created_at, updated_at
        )
        SELECT DISTINCT ON (u.cnpj)
            u.company_name, u.cnpj, u.trade_name, u.cnae_code, u.cnae_description,
            u.company_address_street, u.company_address_number, u.company_address_complement,
            u.company_address_district, u.company_address_city, u.company_address_state,
            u.company_address_zip, u.capital_social, u.company_size, u.legal_nature,
            u.company_phone, u.company_email, u.company_status, u.company_opened_at,
            u.is_simples_nacional, u.is_mei, u.qsa_partners, u.cnaes_secundarios,
            u.company_address_type, u.is_headquarters, u.ibge_code, u.regime_tributario,
            u.simples_desde, u.simples_excluido_em, u.main_partner_name,
            u.main_partner_qualification, u.created_at, NOW()
        FROM users u
        WHERE u.parent_user_id IS NULL
        ORDER BY u.cnpj, u.created_at ASC
    """))

    # Step 2: Create OrgMembership for owners (parent_user_id IS NULL)
    conn.execute(sa.text("""
        INSERT INTO org_memberships (user_id, organization_id, role, joined_at, is_active)
        SELECT u.id, o.id, COALESCE(u.role, 'owner'), u.created_at, u.is_active
        FROM users u
        JOIN organizations o ON u.cnpj = o.cnpj
        WHERE u.parent_user_id IS NULL
    """))

    # Step 3: Create OrgMembership for team members (parent_user_id IS NOT NULL)
    conn.execute(sa.text("""
        INSERT INTO org_memberships (user_id, organization_id, role, invited_by_user_id, joined_at, is_active)
        SELECT u.id, o.id, u.role, u.invited_by_user_id, COALESCE(u.invited_at, u.created_at), u.is_active
        FROM users u
        JOIN users owner_user ON u.parent_user_id = owner_user.id
        JOIN organizations o ON owner_user.cnpj = o.cnpj
        WHERE u.parent_user_id IS NOT NULL
        ON CONFLICT (user_id, organization_id) DO NOTHING
    """))

    # Step 4: Set active_org_id for all users (prefer org where they're owner)
    conn.execute(sa.text("""
        UPDATE users u SET active_org_id = (
            SELECT om.organization_id
            FROM org_memberships om
            WHERE om.user_id = u.id AND om.is_active = true
            ORDER BY (om.role = 'owner') DESC, om.joined_at ASC
            LIMIT 1
        )
    """))

    # Step 5: Link subscriptions to organizations
    conn.execute(sa.text("""
        UPDATE subscriptions s SET organization_id = (
            SELECT o.id
            FROM organizations o
            JOIN users u ON u.cnpj = o.cnpj
            WHERE u.id = s.user_id
            LIMIT 1
        )
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_active_org_id'), table_name='users')
    op.drop_column('users', 'active_org_id')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'organization_id')
    op.drop_index(op.f('ix_org_memberships_user_id'), table_name='org_memberships')
    op.drop_index(op.f('ix_org_memberships_organization_id'), table_name='org_memberships')
    op.drop_index(op.f('ix_org_memberships_id'), table_name='org_memberships')
    op.drop_index('idx_org_membership_org_active', table_name='org_memberships')
    op.drop_table('org_memberships')
    op.drop_index(op.f('ix_org_invitations_token'), table_name='org_invitations')
    op.drop_index(op.f('ix_org_invitations_target_user_id'), table_name='org_invitations')
    op.drop_index(op.f('ix_org_invitations_target_email'), table_name='org_invitations')
    op.drop_index(op.f('ix_org_invitations_organization_id'), table_name='org_invitations')
    op.drop_index(op.f('ix_org_invitations_inviter_user_id'), table_name='org_invitations')
    op.drop_index(op.f('ix_org_invitations_id'), table_name='org_invitations')
    op.drop_table('org_invitations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_cnpj'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
