"""create sysadmin tables with correct order

Revision ID: 95b88f3264bc
Revises: f5cf6463573a
Create Date: 2026-01-30 10:21:36.912434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b88f3264bc'
down_revision: Union[str, None] = 'f5cf6463573a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('active_users_24h', sa.Integer(), nullable=False),
    sa.Column('active_users_7d', sa.Integer(), nullable=False),
    sa.Column('new_registrations', sa.Integer(), nullable=False),
    sa.Column('trial_conversions', sa.Integer(), nullable=False),
    sa.Column('churned_users', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('api_calls_total', sa.Integer(), nullable=False),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=False),
    sa.Column('storage_bytes_used', sa.Numeric(precision=20, scale=0), nullable=False),
    sa.Column('mrr_cents', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('arr_cents', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('new_revenue_cents', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('churned_revenue_cents', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=False),
    sa.Column('p95_response_time_ms', sa.Integer(), nullable=False),
    sa.Column('uptime_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tickets_created', sa.Integer(), nullable=False),
    sa.Column('tickets_resolved', sa.Integer(), nullable=False),
    sa.Column('avg_resolution_time_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('calculation_duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_daily_metrics_date'), 'daily_metrics', ['date'], unique=False)
    op.create_table('system_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('external_auth_provider', sa.String(length=50), nullable=True),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('external_metadata', sa.JSON(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['system_admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_user_id')
    )
    op.create_index(op.f('ix_system_admins_email'), 'system_admins', ['email'], unique=True)
    op.create_index(op.f('ix_system_admins_id'), 'system_admins', ['id'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('related_ticket_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['system_admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_endpoint_date', 'error_logs', ['endpoint', 'created_at'], unique=False)
    op.create_index('idx_error_org_date', 'error_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_error_type_date', 'error_logs', ['error_type', 'created_at'], unique=False)
    op.create_index('idx_error_unresolved', 'error_logs', ['is_resolved', 'created_at'], unique=False)
    op.create_index('idx_error_user_date', 'error_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_endpoint'), 'error_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_error_logs_error_type'), 'error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_id'), 'error_logs', ['id'], unique=False)
    op.create_index(op.f('ix_error_logs_organization_id'), 'error_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_error_logs_user_id'), 'error_logs', ['user_id'], unique=False)
    op.create_table('impersonation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sysadmin_id', sa.Integer(), nullable=False),
    sa.Column('sysadmin_email', sa.String(length=255), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_expire_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sysadmin_id'], ['system_admins.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_impersonation_active', 'impersonation_sessions', ['is_active', 'auto_expire_at'], unique=False)
    op.create_index('idx_impersonation_sysadmin_date', 'impersonation_sessions', ['sysadmin_id', 'started_at'], unique=False)
    op.create_index('idx_impersonation_target_date', 'impersonation_sessions', ['target_user_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_id'), 'impersonation_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_started_at'), 'impersonation_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_sysadmin_id'), 'impersonation_sessions', ['sysadmin_id'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_target_user_id'), 'impersonation_sessions', ['target_user_id'], unique=False)
    op.create_table('system_admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sysadmin_id', sa.Integer(), nullable=False),
    sa.Column('sysadmin_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('was_impersonating', sa.Boolean(), nullable=False),
    sa.Column('impersonation_session_id', sa.Integer(), nullable=True),
    sa.Column('impersonated_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['impersonated_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['impersonation_session_id'], ['impersonation_sessions.id'], ),
    sa.ForeignKeyConstraint(['sysadmin_id'], ['system_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sysadmin_audit_action_date', 'system_admin_audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_sysadmin_audit_entity', 'system_admin_audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_sysadmin_audit_impersonation', 'system_admin_audit_logs', ['was_impersonating', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_admin_audit_logs_action'), 'system_admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_system_admin_audit_logs_created_at'), 'system_admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_admin_audit_logs_id'), 'system_admin_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_admin_audit_logs_sysadmin_id'), 'system_admin_audit_logs', ['sysadmin_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'assigned', 'in_progress', 'waiting_customer', 'resolved', 'closed', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='ticket_priority'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_admin_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('response_time_minutes', sa.Integer(), nullable=True),
    sa.Column('resolution_time_hours', sa.Integer(), nullable=True),
    sa.Column('related_error_log_id', sa.Integer(), nullable=True),
    sa.Column('related_document_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_admin_id'], ['system_admins.id'], ),
    sa.ForeignKeyConstraint(['related_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ticket_assigned', 'support_tickets', ['assigned_to_admin_id', 'status'], unique=False)
    op.create_index('idx_ticket_status_priority', 'support_tickets', ['status', 'priority'], unique=False)
    op.create_index('idx_ticket_user', 'support_tickets', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_support_tickets_assigned_to_admin_id'), 'support_tickets', ['assigned_to_admin_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_category'), 'support_tickets', ['category'], unique=False)
    op.create_index(op.f('ix_support_tickets_created_at'), 'support_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_support_tickets_priority'), 'support_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal_note', sa.Boolean(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_id'), 'ticket_messages', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_priority'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_created_at'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_category'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_assigned_to_admin_id'), table_name='support_tickets')
    op.drop_index('idx_ticket_user', table_name='support_tickets')
    op.drop_index('idx_ticket_status_priority', table_name='support_tickets')
    op.drop_index('idx_ticket_assigned', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_system_admin_audit_logs_sysadmin_id'), table_name='system_admin_audit_logs')
    op.drop_index(op.f('ix_system_admin_audit_logs_id'), table_name='system_admin_audit_logs')
    op.drop_index(op.f('ix_system_admin_audit_logs_created_at'), table_name='system_admin_audit_logs')
    op.drop_index(op.f('ix_system_admin_audit_logs_action'), table_name='system_admin_audit_logs')
    op.drop_index('idx_sysadmin_audit_impersonation', table_name='system_admin_audit_logs')
    op.drop_index('idx_sysadmin_audit_entity', table_name='system_admin_audit_logs')
    op.drop_index('idx_sysadmin_audit_action_date', table_name='system_admin_audit_logs')
    op.drop_table('system_admin_audit_logs')
    op.drop_index(op.f('ix_impersonation_sessions_target_user_id'), table_name='impersonation_sessions')
    op.drop_index(op.f('ix_impersonation_sessions_sysadmin_id'), table_name='impersonation_sessions')
    op.drop_index(op.f('ix_impersonation_sessions_started_at'), table_name='impersonation_sessions')
    op.drop_index(op.f('ix_impersonation_sessions_id'), table_name='impersonation_sessions')
    op.drop_index('idx_impersonation_target_date', table_name='impersonation_sessions')
    op.drop_index('idx_impersonation_sysadmin_date', table_name='impersonation_sessions')
    op.drop_index('idx_impersonation_active', table_name='impersonation_sessions')
    op.drop_table('impersonation_sessions')
    op.drop_index(op.f('ix_error_logs_user_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_organization_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_error_type'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_endpoint'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_index('idx_error_user_date', table_name='error_logs')
    op.drop_index('idx_error_unresolved', table_name='error_logs')
    op.drop_index('idx_error_type_date', table_name='error_logs')
    op.drop_index('idx_error_org_date', table_name='error_logs')
    op.drop_index('idx_error_endpoint_date', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_system_admins_id'), table_name='system_admins')
    op.drop_index(op.f('ix_system_admins_email'), table_name='system_admins')
    op.drop_table('system_admins')
    op.drop_index(op.f('ix_daily_metrics_date'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
