"""add_qsa_partners_and_extended_cnpj_data

Revision ID: ac7c62914c7f
Revises: 0dfa6216e4e5
Create Date: 2026-03-02 20:48:52.033244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7c62914c7f'
down_revision: Union[str, None] = '0dfa6216e4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('qsa_partners', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('cnaes_secundarios', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('company_address_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_headquarters', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('ibge_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('regime_tributario', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('simples_desde', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('simples_excluido_em', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('main_partner_name', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('main_partner_qualification', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'main_partner_qualification')
    op.drop_column('users', 'main_partner_name')
    op.drop_column('users', 'simples_excluido_em')
    op.drop_column('users', 'simples_desde')
    op.drop_column('users', 'regime_tributario')
    op.drop_column('users', 'ibge_code')
    op.drop_column('users', 'is_headquarters')
    op.drop_column('users', 'company_address_type')
    op.drop_column('users', 'cnaes_secundarios')
    op.drop_column('users', 'qsa_partners')
    # ### end Alembic commands ###
