"""add initial balance and bank account tables

Revision ID: ed50e31a4d49
Revises: 83d1d05da3fc
Create Date: 2026-03-03 13:14:46.922779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed50e31a4d49'
down_revision: Union[str, None] = '83d1d05da3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('bank_code', sa.String(length=10), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('agency', sa.String(length=20), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('account_nickname', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_bank_accounts_id'), 'org_bank_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_org_bank_accounts_organization_id'), 'org_bank_accounts', ['organization_id'], unique=False)
    op.create_table('org_initial_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('short_term_investments', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('accounts_receivable', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('inventory', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('prepaid_expenses', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('long_term_receivables', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('long_term_investments', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('fixed_assets_land', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('fixed_assets_buildings', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('fixed_assets_machinery', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('fixed_assets_vehicles', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('fixed_assets_furniture', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('fixed_assets_computers', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('fixed_assets_other', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('intangible_assets', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('accumulated_amortization', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('suppliers_payable', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('short_term_loans', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('labor_obligations', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('tax_obligations', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('other_current_liabilities', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('long_term_loans', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('long_term_financing', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('bank_account_balances', sa.JSON(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'reference_date', name='uq_org_initial_balance')
    )
    op.create_index(op.f('ix_org_initial_balances_id'), 'org_initial_balances', ['id'], unique=False)
    op.create_index(op.f('ix_org_initial_balances_organization_id'), 'org_initial_balances', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_initial_balances_organization_id'), table_name='org_initial_balances')
    op.drop_index(op.f('ix_org_initial_balances_id'), table_name='org_initial_balances')
    op.drop_table('org_initial_balances')
    op.drop_index(op.f('ix_org_bank_accounts_organization_id'), table_name='org_bank_accounts')
    op.drop_index(op.f('ix_org_bank_accounts_id'), table_name='org_bank_accounts')
    op.drop_table('org_bank_accounts')
    # ### end Alembic commands ###
