"""add_sysadmin_infrastructure

Revision ID: f5cf6463573a
Revises: manual_api_keys_001
Create Date: 2026-01-29 10:51:40.925795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5cf6463573a'
down_revision: Union[str, None] = 'manual_api_keys_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_comment='Custom permissions JSON',
               existing_nullable=True)
    op.alter_column('api_keys', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Optional expiration date',
               existing_nullable=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_index('idx_audit_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_document_id', table_name='audit_logs')
    op.drop_index('idx_audit_user_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_index('idx_documents_category', table_name='documents')
    op.drop_index('idx_documents_department', table_name='documents')
    op.drop_index('idx_documents_user_department', table_name='documents')
    op.drop_index('idx_documents_user_status_date', table_name='documents')
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_department'), 'documents', ['department'], unique=False)
    op.alter_column('user_claims', 'claim_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Permission claim (e.g., documents.delete)',
               existing_nullable=False)
    op.alter_column('user_claims', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Optional expiration',
               existing_nullable=True)
    op.create_index(op.f('ix_user_claims_id'), 'user_claims', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_claims_id'), table_name='user_claims')
    op.alter_column('user_claims', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Optional expiration',
               existing_nullable=True)
    op.alter_column('user_claims', 'claim_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Permission claim (e.g., documents.delete)',
               existing_nullable=False)
    op.drop_index(op.f('ix_documents_department'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.create_index('idx_documents_user_status_date', 'documents', ['user_id', 'status', 'upload_date'], unique=False)
    op.create_index('idx_documents_user_department', 'documents', ['user_id', 'department'], unique=False)
    op.create_index('idx_documents_department', 'documents', ['department'], unique=False)
    op.create_index('idx_documents_category', 'documents', ['category'], unique=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('idx_audit_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_document_id', 'audit_logs', ['document_id'], unique=False)
    op.create_index('idx_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.alter_column('api_keys', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Optional expiration date',
               existing_nullable=True)
    op.alter_column('api_keys', 'permissions',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Custom permissions JSON',
               existing_nullable=True)
    # ### end Alembic commands ###
